"""create recibos table

Revision ID: 0e4542704858
Revises: da8a23b32582
Create Date: 2026-01-10 19:03:18.335800

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e4542704858"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recibos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("total", sa.Float(), nullable=False),
        sa.Column("metodo", sa.String(length=50), nullable=False),
        sa.Column("parcelas", sa.Integer(), nullable=False),
        sa.Column("informacoes_adicionais", sa.String(), nullable=True),
        sa.Column("valor_parcela", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recibos_id"), "recibos", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recibos_id"), table_name="recibos")
    op.drop_table("recibos")
    # ### end Alembic commands ###
